### ISSUE TITLE
Application crashes when item ID is not found in database

### ISSUE THREAD

**Issue by vbudi000** [ibm-cloud-architecture/refarch-cloudnative-bff-inventory#4]
When the item ID is not found, the microservice return a null string. However the bff *always* parse the return value as a JSON string, hence  when the return value is null it crashes. Suggestion is to check whether the result is null and then either return an error or insert an empty JSON object `{}` in /inventory/routes/itemservices.js

```
                        if (0 === body.length) {
                             body = "{}";
                        }
                        var bodyJson = JSON.parse(body);
```

or 

```
                        if (0 === body.length) {
                             return res.send({"error":"item not found"});
                        }
                        var bodyJson = JSON.parse(body);
```

**Comment by ssibm** [comment]
fixed in r1defect
